In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/boston-housing-dataset/housing.csv


In [3]:
file='/kaggle/input/boston-housing-dataset/housing.csv'

In [4]:
df=pd.read_csv(file)

In [5]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
x=pd.DataFrame(np.c_[df['LSTAT'],df['RM']],columns=['LSTAT','RM'])
y=df['MEDV']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [7]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
degree=2
polynomial_features=PolynomialFeatures(degree=degree)


In [12]:
x_train_poly=polynomial_features.fit_transform(x_train)
print(x_train_poly)

[[  1.         5.21       6.43      27.1441    33.5003    41.3449  ]
 [  1.        12.04       6.176    144.9616    74.35904   38.142976]
 [  1.        10.21       5.682    104.2441    58.01322   32.285124]
 ...
 [  1.         5.99       6.635     35.8801    39.74365   44.023225]
 [  1.        23.27       6.629    541.4929   154.25683   43.943641]
 [  1.        10.63       6.405    112.9969    68.08515   41.024025]]


In [14]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [15]:
model.fit(x_train_poly,y_train)

LinearRegression()

In [16]:
x_test_poly=polynomial_features.fit_transform(x_test)
